project:
  type: default
  execute-dir: project

bibliography: "misc/references.bib"

#################
# Knitr options #
#################
knitr:
  opts_chunk:
    dpi: 96
    fig.retina: 2
    results: hold
    tidy: styler
    tidy-opts:
      strict: false
  opts_knit:
    dev: !expr 'c("ragg_png", "cairo_pdf")'

##################
# Format options #
##################
format:
  html:
    theme:
    - darkly
    embed-resources: false
    code-fold: true
    code-summary: Code
    code-link: true
    code-block-bg: true
    css: css/style.css
    df-print: paged
    toc: true
    fig-format: png
    keep-md: false
    execute:
      echo: true
      warning: true
      message: true
    knitr:
      opts_chunk: 
        dev: ragg_png
  pdf:
    documentclass: scrreprt
    toc: true
    lof: true
    lot: true
    fig-format: pdf
    keep-tex: false
    df-print: kable
    execute:
      echo: false
      warning: false
    knitr:
      opts_chunk: 
        dev: pdf
    code-block-bg: true
    include-in-header: 
      text: |
        \usepackage{fvextra}
        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,breakanywhere,commandchars=\\\{\}}
  docx:
    reference-doc: misc/template.docx
    page-width: 8.3
    toc: true
    fig-format: png
    df-print: kable
    execute:
      echo: false
      warning: false
    knitr:
      opts_chunk: 
        dev: ragg_png

params:
  author: "aba"