project:
  type: default
  output-dir: "_book"
  execute-dir: project
  post-render: 
    - R/collect_module_results.R

bibliography: "misc/references.bib"
csl: "misc/nature.csl"

#################
# Knitr options #
#################
knitr:
  opts_chunk:
    fig-width: 6
    dpi: 96
    fig.retina: 2
    results: hold
    timeit: null
    tidy: styler
    tidy-opts:
      strict: false
  opts_knit:
    dev: !expr 'c("ragg_png", "cairo_pdf")'

##################
# Format options #
##################
format:
  html:
    theme:
    - sandstone
    embed-resources: false
    code-fold: true
    code-summary: Code
    code-link: true
    code-block-bg: true
    css: css/style.css
    df-print: kable
    toc: true
    toc-depth: 2
    fig-format: png
    keep-md: false
    execute:
      echo: true
      warning: true
      message: true
    knitr:
      opts_chunk: 
        dev: ragg_png
  # pdf:
  #   documentclass: scrreprt
  #   toc: true
  #   toc-depth: 2
  #   lof: true
  #   lot: true
  #   fig-format: pdf
  #   keep-tex: false
  #   df-print: kable
  #   execute:
  #     echo: false
  #     warning: false
  #   knitr:
  #     opts_chunk:
  #       dev: pdf
  #   code-block-bg: true
  #   include-in-header:
  #     text: |
  #       \usepackage{fvextra}
  #       \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,breakanywhere,commandchars=\\\{\}}
  # docx:
  #   reference-doc: misc/template.docx
  #   page-width: 8.3
  #   toc: true
  #   toc-depth: 2
  #   fig-format: png
  #   df-print: kable
  #   execute:
  #     echo: false
  #     warning: false
  #   knitr:
  #     opts_chunk:
  #       dev: ragg_png

profile: 
  default: default