###########
# Project #
###########

project:
  type: "default"
  output-dir: "_book"
  execute-dir: "project"
  post-render: 
    - "R/collect_module_results.R"

bibliography: "misc/references.bib"
csl: "misc/nature.csl"

###########
# Profile #
###########

profile: 
  default: "default"

#################
# Knitr options #
#################
knitr:
  opts_chunk:
    fig-width: 6
    dpi: 96
    fig.retina: 2
    results: "hold"
    timeit: null
    tidy: "styler"
    tidy-opts:
      strict: false

##################
# Format options #
##################

format:
  html:
    theme:
    - "sandstone"
    embed-resources: false
    code-fold: true
    code-summary: "Code"
    code-link: true
    code-block-bg: true
    css: "css/style.css"
    df-print: "kable"
    toc: true
    toc-depth: 2
    fig-format: "png"
    keep-md: true
    #execute:
    #  echo: false
    #  message: false
    #  warning: false
    knitr:
      opts_chunk: 
        dev:
        - "ragg_png"
        - "cairo_pdf"
  # pdf:
  #   documentclass: "scrreprt"
  #   code-block-bg: true
  #   df-print: "kable"
  #   toc: true
  #   toc-depth: 2
  #   lof: true
  #   lot: true
  #   fig-format: "pdf"
  #   keep-tex: false
  #   #execute:
  #   #  echo: false
  #   #  message: false
  #   #  warning: false
  #   knitr:
  #     opts_chunk: 
  #       dev:
  #       - "cairo_pdf"
  #       - "ragg_png"
  #   include-in-header:
  #     text: |
  #       \usepackage{fvextra}
  #       \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,breakanywhere,commandchars=\\\{\}}
  # docx:
  #   reference-doc: "misc/template.docx"
  #   page-width: 8.3
  #   code-block-bg: true
  #   df-print: "kable"
  #   toc: true
  #   toc-depth: 2
  #   fig-format: "png"
  #   #execute:
  #   #  echo: false
  #   #  message: false
  #   #  warning: false
  #   knitr:
  #     opts_chunk: 
  #       dev:
  #       - "ragg_png"
  #       - "cairo_pdf"

#########
# Other #
#########

# Date
date: "now"
date-modified: "last-modified"
date-format: "DD-MM-YYYY HH:mm:ss"
